language: cpp

git:
  depth: 3

dist: focal

jobs:
  include:
    - name: "gcc-9 (Make)"
      addons:
        apt:
          update: true
          packages:
            - cmake
            - g++-9
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - uuid-dev
            - libunwind8-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libcgal-qt5-dev
            - libcgal-dev
      env:
        - CC=gcc-9
        - CXX=g++-9
        - GENERATOR="Unix Makefiles"
    - name: "gcc-9 (Ninja)"
      addons:
        apt:
          update: true
          packages:
            - cmake
            - g++-9
            - ninja-build
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - uuid-dev
            - libunwind8-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libcgal-qt5-dev
            - libcgal-dev
      env:
        - CC=gcc-9
        - CXX=g++-9
        - GENERATOR=Ninja
    - name: "clang-10 (Make)"
      addons:
        apt:
          update: true
          packages:
            - cmake
            - clang-10
            #- libiomp-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - uuid-dev
            - libunwind8-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libcgal-qt5-dev
            - libcgal-dev
      env:
        - CC=clang-8
        - CXX=clang++-8
        - GENERATOR="Unix Makefiles"

install:
  - . .travis/install-cuda-focal.sh

script:
  - mkdir build && cd build
  - /usr/bin/cmake .. -G"$GENERATOR" -DCMAKE_BUILD_TYPE=Release
  - /usr/bin/cmake --build . --target HelloTravis
  - ./HelloTravis
