language: cpp

git:
  depth: 3

dist: focal

jobs:
  include:
    - name: "gcc-make"
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
      env:
        - CC=gcc
        - CXX=g++
        - GENERATOR="Unix Makefiles"
    - name: "clang-make"
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
      env:
        - CC=clang
        - CXX=clang++
        - GENERATOR="Unix Makefiles"
    - name: "gcc-ninja"
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
      env:
        - CC=gcc
        - CXX=g++
        - GENERATOR="Ninja"

script:
  - mkdir build && cd build
  - cmake .. -G"$GENERATOR" -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --target HelloTravis
  - ls -alF
  - ./HelloTravis
