
trigger:
- master

pr:
- master

strategy:
  matrix:
    windows-10:
      agentName: BEIGUAN
      

pool:
  name: 'default'
  demands:
  - Agent.Name -equals $(agentName)

steps:
- task: CMake@1
  inputs:
    cmakeArgs: ..
- script: |
    cd build
    cmake --build .
  displayName: 'build'
