
trigger:
- master

pr:
- master

jobs:
- job: windows
  strategy:
    matrix:
      windows-10:
        agentName: BEIGUAN
      ubuntu-1804:
        agentName: benga

  pool:
    name: 'default'
    demands:
    - Agent.Name -equals $(agentName)

  steps:
  - task: CMake@1
    displayName: 'CMake Configure'
    inputs:
      cmakeArgs: '.. -G"$(generator)" -A"x64" -DCMAKE_BUILD_TYPE=$(configuration)'
  - task: CMake@1
    displayName: 'CMake Build'
    inputs:
      cmakeArgs: '--build . --config $(configuration)'
